server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/henrique-pignatari/spring-cloud-micro-services
          search-paths:
            - 'configurations*'
            - 'configurations/greeting-service*'

# this down points to a /resources/config folder that holds the configuration files
#  profiles:
#    active:
#      - native